# Generated by Django 3.2.9 on 2021-12-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=150, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название произвидение')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('subscription', models.BooleanField(default=False, verbose_name='Подписка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('audiobook_file', models.FileField(blank=True, null=True, upload_to='audiobooks')),
                ('size_of_audio', models.FloatField(default='0.00', verbose_name='Размер аудиофайла')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('published_date', models.CharField(max_length=150, verbose_name='Дата публикации')),
                ('age_limit', models.IntegerField(default='1992', verbose_name='Возрастной лимит')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
            },
        ),
    ]
