# Generated by Django 3.2.9 on 2021-12-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_composition_audiobook_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='audiobook_file',
            field=models.FileField(blank=True, null=True, upload_to='audiobooks'),
        ),
    ]
