# Generated by Django 3.2.9 on 2021-12-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_composition_audiobook_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='duration_of_audio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность сказки (В секундах)'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='age_limit',
            field=models.IntegerField(default='0', verbose_name='Возрастной лимит'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='audiobook_file',
            field=models.FileField(blank=True, null=True, upload_to='audiobooks', verbose_name='Аудио сказки'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Обложка сказки'),
        ),
    ]
