# Generated by Django 3.2.9 on 2021-12-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211207_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='duration_of_audio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность сказки (В секундах)'),
        ),
    ]
