# Generated by Django 3.2.9 on 2021-12-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211207_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Catalog', 'verbose_name_plural': 'Catalogs'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(null=True, upload_to='audiobook/catalog/image'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='audiobook_file',
            field=models.FileField(blank=True, null=True, upload_to='audiobook/composition/audio', verbose_name='Аудио сказки'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='audiobook/composition/images', verbose_name='Обложка сказки'),
        ),
    ]
