# Generated by Django 3.2.9 on 2023-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211207_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(null=True, upload_to='audiobooks/catalog/image', verbose_name='Обложка катлога'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='audiobook_file',
            field=models.FileField(blank=True, null=True, upload_to='audiobooks/composition/audio', verbose_name='Аудио сказки'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='audiobooks/composition/images', verbose_name='Обложка сказки'),
        ),
    ]
